# Generated by Django 5.1.1 on 2024-10-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_role_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.TextField(max_length=255)),
                ('hours', models.TextField(max_length=255)),
            ],
        ),
    ]
