# Generated by Django 5.1.1 on 2024-10-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_venues'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('type', models.CharField(max_length=254)),
                ('duration', models.IntegerField(max_length=20)),
                ('price', models.IntegerField(max_length=255)),
            ],
        ),
    ]
