# Generated by Django 5.1.1 on 2024-10-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='duration',
            field=models.CharField(max_length=20),
        ),
    ]
