# Generated by Django 5.1.1 on 2024-10-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_tickets_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
