# Generated by Django 5.1.1 on 2024-10-15 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_headset_barcodeno_alter_venues_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245)),
                ('modelNo', models.CharField(max_length=245)),
                ('serialNo', models.CharField(max_length=245)),
                ('barcodeNo', models.IntegerField()),
                ('assignedVenue', models.CharField(max_length=20)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.venues')),
            ],
        ),
    ]
