# Generated by Django 5.1.1 on 2024-10-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_tablet'),
    ]

    operations = [
        migrations.AddField(
            model_name='venues',
            name='locationdefine',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
